rails/queries_active_records/config/routes.rb
Rails.application.routes.draw do
  resources :productos
  resources :referencia

end

rails/queries_active_records/app/models/producto.rb
class Producto < ActiveRecord::Base
end

rails/queries_active_records/app/models/referencium.rb
class Referencium < ActiveRecord::Base
end

rails/queries_active_records/app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]

  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all # SELECT * FROM producto
    #@productos = Producto.find(10) #encontrar por ID
    #@productos = Producto.take(10) #SELECT * FROM tabla limit 10
    #@productos = Producto.first #Primer registro
    #@productos = Producto.last  #Último registro
    #@productos = Producto.find_by_color("blanco") #SELECT * FROM producto WHERE color = "blanco"
    #@productos = Producto.where(talla: ["s", "l"]) #SELECT * FROM producto WHERE color = "blanco" OR talla = "l"
    #@productos = Producto.where.not(talla: ["s", "l"]) #?
    #@productos = Producto.where.not(talla: ["s", "l"]) #?
    #@productos = Producto.order(precio: :asc) #SELECT * FROM producto ORDER BY  precio ASC
    #@productos = Producto.select(:costo, :precio) #SELECT producto.costo, producto.precio FROM producto
    #@productos = Producto.limit(5).offset(10)
    #@productos = Producto.limit(5).offset(10)
    #@productos = Producto.group(:talla)
    #@productos = Producto.group(:tipo).having("sum(precio) < ?", 2800000)
    # SELECT * FROM producto WHERE SUM(precio) > 2800000 GRUOP BY tipo
    #@productos = Producto.all.readonly !important security!
    #@productos = Producto.includes(:categoria).limit(10) #? Relaciones
    #@productos = Producto.where("cantidad > ? AND tipo = ?", 100, "hombre")
    #@productos = Producto.where("descripcion like  ? ",  "%niño%")
    #pluck, sum, minimum, maximum, average

  end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:referencia, :color, :talla, :categoria, :ripo, :marca, :descripcion, :tela, :cantidad, :costo, :precio)
    end
end

rails/queries_active_records/app/controllers/referencia_controller.rb
class ReferenciaController < ApplicationController
  before_action :set_referencium, only: [:show, :edit, :update, :destroy]

  # GET /referencia
  # GET /referencia.json
  def index
    @referencia = Referencium.all
  end

  # GET /referencia/1
  # GET /referencia/1.json
  def show
  end

  # GET /referencia/new
  def new
    @referencium = Referencium.new
  end

  # GET /referencia/1/edit
  def edit
  end

  # POST /referencia
  # POST /referencia.json
  def create
    @referencium = Referencium.new(referencium_params)

    respond_to do |format|
      if @referencium.save
        format.html { redirect_to @referencium, notice: 'Referencium was successfully created.' }
        format.json { render :show, status: :created, location: @referencium }
      else
        format.html { render :new }
        format.json { render json: @referencium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /referencia/1
  # PATCH/PUT /referencia/1.json
  def update
    respond_to do |format|
      if @referencium.update(referencium_params)
        format.html { redirect_to @referencium, notice: 'Referencium was successfully updated.' }
        format.json { render :show, status: :ok, location: @referencium }
      else
        format.html { render :edit }
        format.json { render json: @referencium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /referencia/1
  # DELETE /referencia/1.json
  def destroy
    @referencium.destroy
    respond_to do |format|
      format.html { redirect_to referencia_url, notice: 'Referencium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_referencium
      @referencium = Referencium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def referencium_params
      params.require(:referencium).permit(:color, :talla, :categoria, :ripo, :marca, :descripcion, :tela, :cantidad, :costo, :precio)
    end
end

rails/queries_active_records/app/helpers/productos_helper.rb
module ProductosHelper
end

rails/queries_active_records/app/helpers/referencia_helper.rb
module ReferenciaHelper
end

rails/queries_active_records/app/views/referencia/_form.html.erb
<%= form_for(@referencium) do |f| %>
  <% if @referencium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@referencium.errors.count, "error") %> prohibited this referencium from being saved:</h2>

      <ul>
      <% @referencium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :talla %><br>
    <%= f.text_field :talla %>
  </div>
  <div class="field">
    <%= f.label :categoria %><br>
    <%= f.text_field :categoria %>
  </div>
  <div class="field">
    <%= f.label :ripo %><br>
    <%= f.text_field :ripo %>
  </div>
  <div class="field">
    <%= f.label :marca %><br>
    <%= f.text_field :marca %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :tela %><br>
    <%= f.text_field :tela %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br>
    <%= f.text_field :cantidad %>
  </div>
  <div class="field">
    <%= f.label :costo %><br>
    <%= f.text_field :costo %>
  </div>
  <div class="field">
    <%= f.label :precio %><br>
    <%= f.text_field :precio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/queries_active_records/app/views/referencia/edit.html.erb
<h1>Editing Referencium</h1>

<%= render 'form' %>

<%= link_to 'Show', @referencium %> |
<%= link_to 'Back', referencia_path %>

rails/queries_active_records/app/views/referencia/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Referencia</h1>

<table>
  <thead>
    <tr>
      <th>Color</th>
      <th>Talla</th>
      <th>Categoria</th>
      <th>Ripo</th>
      <th>Marca</th>
      <th>Descripcion</th>
      <th>Tela</th>
      <th>Cantidad</th>
      <th>Costo</th>
      <th>Precio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @referencia.each do |referencium| %>
      <tr>
        <td><%= referencium.color %></td>
        <td><%= referencium.talla %></td>
        <td><%= referencium.categoria %></td>
        <td><%= referencium.ripo %></td>
        <td><%= referencium.marca %></td>
        <td><%= referencium.descripcion %></td>
        <td><%= referencium.tela %></td>
        <td><%= referencium.cantidad %></td>
        <td><%= referencium.costo %></td>
        <td><%= referencium.precio %></td>
        <td><%= link_to 'Show', referencium %></td>
        <td><%= link_to 'Edit', edit_referencium_path(referencium) %></td>
        <td><%= link_to 'Destroy', referencium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Referencium', new_referencium_path %>

rails/queries_active_records/app/views/referencia/new.html.erb
<h1>New Referencium</h1>

<%= render 'form' %>

<%= link_to 'Back', referencia_path %>

rails/queries_active_records/app/views/referencia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Color:</strong>
  <%= @referencium.color %>
</p>

<p>
  <strong>Talla:</strong>
  <%= @referencium.talla %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @referencium.categoria %>
</p>

<p>
  <strong>Ripo:</strong>
  <%= @referencium.ripo %>
</p>

<p>
  <strong>Marca:</strong>
  <%= @referencium.marca %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @referencium.descripcion %>
</p>

<p>
  <strong>Tela:</strong>
  <%= @referencium.tela %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @referencium.cantidad %>
</p>

<p>
  <strong>Costo:</strong>
  <%= @referencium.costo %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @referencium.precio %>
</p>

<%= link_to 'Edit', edit_referencium_path(@referencium) %> |
<%= link_to 'Back', referencia_path %>