rails/torre/config/routes.rb
Rails.application.routes.draw do

   root 'all#index'
   resources :towers
   resources :apartments
   resources :people

end

rails/torre/app/models/apartment.rb
class Apartment < ActiveRecord::Base
	belongs_to :tower
	has_many :people
end

rails/torre/app/models/tower.rb
class Tower < ActiveRecord::Base
	has_many :apartments
end

rails/torre/app/controllers/all_controller.rb
class AllController < ApplicationController
	def index
		@people = Person.all
		@apartment = Apartment.all
		@tower = Tower.all
	end
	private
	def user_params
		params.permit(:config).(:people, :apartment, :tower)
	end
end

rails/torre/app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
	def index
		@apartment = Apartment.all
	end
	def new
		@apartment = Apartment.new
	end
	def create
		@apartment = Apartment.new(apartment_params)
		@apartment.save
		redirect_to apartments_path
	end
	def edit
		@apartment = Apartment.find(params[:id])
	end
	def update
		@apartment = Apartment.find(params[:id])
		@apartment.update(apartment_params)
		redirect_to apartments_path
	end
	def show
		@apartment = Apartment.find(params[:id])
	end
	def destroy
		@apartment = Apartment.find(params[:id])
		@apartment.destroy
		redirect_to apartments_path
	end
	private
	def apartment_params
		params.require(:apartment).permit(:name, :floor, :tower_id)
	end
end

rails/torre/app/controllers/people_controller.rb
class PeopleController < ApplicationController
	def index
		@person = Person.all
	end
	def new
		@person = Person.new
	end
	def create
		@person = Person.new(person_params)
		@person.save
		redirect_to people_path
	end
	def edit
		@person = Person.find(params[:id])
	end
	def update
		@person = Person.find(params[:id])
		@person.update(person_params)
		redirect_to people_path
	end
	def show
		@person = Person.find(params[:id])
	end
	def destroy
		@person = Person.find(params[:id])
		@person.destroy
		redirect_to people_path
	end
	private
	def person_params
		params.require(:person).permit(:name, :document, :apartment_id)
	end
end

rails/torre/app/controllers/person_controller.rb
class PersonController < ApplicationController
	def index
		@person = Person.all
	end
	def new
		@person = Person.new
	end
	def create
		@person = Person.new(person_params)
		@person.save
		redirect_to persons_path
	end
	def edit
		@person = Person.find(params[:id])
	end
	def update
		@person = Person.find(params[:id])
		@person.update(person_params)
		redirect_to persons_path
	end
	def show
		@person = Person.find(params[:id])
	end
	def destroy
		@person = Person.find(params[:id])
		@person.destroy
		redirect_to persons_path
	end
	private
	def person_params
		params.require(:person).permit(:name, :document)
	end
end

rails/torre/app/controllers/towers_controller.rb
class TowersController < ApplicationController
	def index
		@tower = Tower.all
	end
	def new
		@tower = Tower.new
	end
	def create
		@tower = Tower.new(tower_params)
		@tower.save
		redirect_to towers_path
	end
	def edit
		@tower = Tower.find(params[:id])
	end
	def update
		@tower = Tower.find(params[:id])
		@tower.update(tower_params)
		redirect_to towers_path
	end
	def show
		@tower = Tower.find(params[:id])
	end
	def destroy
		@tower = Tower.find(params[:id])
		@tower.destroy
		redirect_to towers_path
	end
	private
	def tower_params
		params.require(:tower).permit(:name, :guard)
	end
end

rails/torre/app/helpers/all_helper.rb
module AllHelper
end

rails/torre/app/helpers/person_helper.rb
module PersonHelper
end

rails/torre/app/helpers/towers_helper.rb
module TowersHelper
end

rails/torre/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Torre</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

rails/torre/app/views/towers/edit.html.erb
<h1>Editar Torre</h1>

<%= form_for @tower do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :guard %>
	<%= f.text_field :guard %>
	<%= f.submit %>
<% end %>	

rails/torre/app/views/towers/index.html.erb
<h1>Todas las torres</h1>

<%= link_to "Crear torre", new_tower_path %>
<%= link_to "Ir a root", root_path %>
<ul>
<% @tower.each do |tower| %>
	<li>
	<%= tower.name %><%= link_to "Editar", edit_tower_path(tower) %><%= link_to "Eliminar", tower_path(tower) , method: :delete, data: { confirm: "Sure?"} %>
		<ul>
			<Li>
			<%= tower.guard %>		
			</Li>
		</ul>
	</li>
<% end %>	
</ul>

rails/torre/app/views/towers/new.html.erb
<h1>Crear nueva torre</h1>
<%= link_to "Ir a root", root_path %>
<%= form_for @tower do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :guard %>
	<%= f.text_field :guard %>
	<%= f.submit %>
<% end %>	