rails/colegio/config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :teachers
  resources :subjects
  resources :students
  resources :homeworks
  resources :answers
  resources :enrollments

end

rails/colegio/app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :student
	belongs_to :homework
	belongs_to :subject
end

rails/colegio/app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
	belongs_to :student
	belongs_to :subject
end

rails/colegio/app/models/homework.rb
class Homework < ActiveRecord::Base
	belongs_to :subject
end

rails/colegio/app/models/student.rb
class Student < ActiveRecord::Base
	has_many :enrollments
	has_many :subjects, :through => :enrollments
end

rails/colegio/app/models/subject.rb
class Subject < ActiveRecord::Base
	belongs_to :teacher
	has_many :homeworks
	has_many :enrollments
	has_many :students, :through => :enrollments
end

rails/colegio/app/models/teacher.rb
class Teacher < ActiveRecord::Base
	belongs_to :subject
end

rails/colegio/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	def index
		@answer = Answer.all
	end
	def new
		@answer = Answer.new
	end
	def create
		@answer = Answer.new(homework_params)
		@answer.save
		@answer.update_column(:subject_id, @answer.homework.subject.id)
		redirect_to answers_path
	end
	def edit
		@answer = Answer.find(params[:id])
	end
	def update
		@answer = Answer.find(params[:id])
		@answer.update(homework_params)
		redirect_to answers_path
	end
	def show
		@answer = Answer.find(params[:id])
		redirect_to answers_path
	end
	def destroy
		@answer = Answer.find(params[:id])
		@answer.destroy
		redirect_to answers_path
	end
	def homework_params
		params.require(:answer).permit(:answer, :student_id, :homework_id)
	end
end

rails/colegio/app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
	def index
		@enrollment = Enrollment.all
	end
	def new
		@enrollment = Enrollment.new
	end
	def create
		@enrollment = Enrollment.new(enrollment_params)
		@enrollment.save
		redirect_to enrollments_path
	end
	def edit
		@enrollment = Enrollment.find(params[:id])
	end
	def update
		@enrollment = Enrollment.find(params[:id])
		@enrollment.update(enrollment_params)
		redirect_to enrollments_path
	end
	def show
		@enrollment = Enrollment.find(params[:id])
		redirect_to enrollments_path
	end
	def destroy
		@enrollment = Enrollment.find(params[:id])
		@enrollment.destroy
		redirect_to enrollments_path
	end
	def enrollment_params
		params.require(:enrollment).permit(:student_id, :subject_id)
	end		
end

rails/colegio/app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
	def index
		@homework = Homework.all
	end
	def new
		@homework = Homework.new
	end
	def create
		@homework = Homework.new(homework_params)
		@homework.save
		redirect_to homeworks_path
	end
	def edit
		@homework = Homework.find(params[:id])
	end
	def update
		@homework = Homework.find(params[:id])
		@homework.update(homework_params)
		redirect_to homeworks_path
	end
	def show
		@homework = Homework.find(params[:id])
		redirect_to homeworks_path
	end
	def destroy
		@homework = Homework.find(params[:id])
		@homework.destroy
		redirect_to homeworks_path
	end
	def homework_params
		params.require(:homework).permit(:text, :final_date, :subject_id)
	end		
end

rails/colegio/app/controllers/student_subjects_controller.rb
class student_subjectSubjectsController < ApplicationController
	def index
		@student_subject = Student_subject.all
	end
	def new
		@student_subject = Student_subject.new
	end
	def create
		@student_subject = Student_subject.new(student_subject_params)
		@student_subject.save
		redirect_to student_subjects_path
	end
	def edit
		@student_subject = Student_subject.find(params[:id])
	end
	def update
		@student_subject = Student_subject.find(params[:id])
		@student_subject.update(student_subject_params)
		redirect_to student_subjects_path
	end
	def show
		@student_subject = Student_subject.find(params[:id])
		redirect_to student_subjects_path
	end
	def destroy
		@student_subject = Student_subject.find(params[:id])
		@student_subject.destroy
		redirect_to student_subjects_path
	end
	def student_subject_params
		params.require(:student_subject).permit(:student_id, :subject_id)
	end	
end

rails/colegio/app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def index
		@student = Student.all
	end
	def new
		@student = Student.new
	end
	def create
		@student = Student.new(student_params)
		@student.save
		redirect_to students_path
	end
	def edit
		@student = Student.find(params[:id])
	end
	def update
		@student = Student.find(params[:id])
		@student.update(student_params)
		redirect_to students_path
	end
	def show
		@student = Student.find(params[:id])
		redirect_to students_path
	end
	def destroy
		@student = Student.find(params[:id])
		@student.destroy
		redirect_to students_path
	end
	def student_params
		params.require(:student).permit(:name, :surname, :document)
	end	
end

rails/colegio/app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
	def index
		@subject = Subject.all
	end
	def new
		@subject = Subject.new
	end
	def create
		@subject = Subject.new(subject_params)
		@subject.save
		redirect_to subjects_path
	end
	def edit
		@subject = Subject.find(params[:id])
	end
	def update
		@subject = Subject.find(params[:id])
		@subject.update(subject_params)
		redirect_to subjects_path
	end
	def show
		@subject = Subject.find(params[:id])
		redirect_to subjects_path
	end
	def destroy
		@subject = Subject.find(params[:id])
		@subject.destroy
		redirect_to subjects_path
	end
	def subject_params
		params.require(:subject).permit(:name)
	end	
end

rails/colegio/app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
	def index
		@teacher = Teacher.all
	end
	def new
		@teacher = Teacher.new
	end
	def create
		@teacher = Teacher.new(teacher_params)
		@teacher.save
		redirect_to teachers_path
	end
	def edit
		@teacher = Teacher.find(params[:id])
	end
	def update
		@teacher = Teacher.find(params[:id])
		@teacher.update(teacher_params)
		redirect_to teachers_path
	end
	def show
		@teacher = Teacher.find(params[:id])
		redirect_to teachers_path
	end
	def destroy
		@teacher = Teacher.find(params[:id])
		@teacher.destroy
		redirect_to teachers_path
	end
	def teacher_params
		params.require(:teacher).permit(:name, :surname, :document, :subject_id)
	end
end

rails/colegio/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

rails/colegio/app/helpers/answers_helper.rb
module AnswersHelper
end

rails/colegio/app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

rails/colegio/app/helpers/entrollments_helper.rb
module EntrollmentsHelper
end

rails/colegio/app/helpers/homeworks_helper.rb
module HomeworksHelper
end

rails/colegio/app/helpers/student_subjects_helper.rb
module StudentSubjectsHelper
end

rails/colegio/app/helpers/students_helper.rb
module StudentsHelper
end

rails/colegio/app/helpers/subjects_helper.rb
module SubjectsHelper
end

rails/colegio/app/helpers/teachers_helper.rb
module TeachersHelper
end

rails/colegio/app/helpers/welcome_helper.rb
module WelcomeHelper
end

rails/colegio/app/views/answers/index.html.erb
<h1>Lista de respuestas</h1>
<ul>
<% @answer.each do |a| %>
	<li>
		<% if a.subject %>
			<%= a.homework.text %>( <%= a.subject.name %>) <strong>--:</strong> <%= a.answer %>
		<% end %>
	</li>
<% end %>
</ul>

rails/colegio/app/views/answers/new.html.erb
<h1>Nueva respuesta</h1>

<%= form_for @answer do |f| %>
	<%= f.label :student_id%>
	<%= f.select(:student_id, Student.all.collect {|u| [u.name, u.id]}) %>
	<%= f.label :homework_id%>
	<%= f.select(:homework_id, Homework.all.collect {|u| [u.text, u.id]}) %>
	<%= f.label :answer%>
	<%= f.text_field :answer%>
	<%= f.submit %>
<% end %>

rails/colegio/app/views/homeworks/edit.html.erb
<h1>Editar tarea par estudiantes</h1>

<%= form_for @homework do |f| %>
	<%= f.label :text %>
	<%= f.text_field :text %>
	<%= f.label :final_date %>
	<%= f.date_field :final_date %>
	<%= f.label :subject_id %>
	<%= f.select(:subject_id, Subject.all.collect {|u| [u.name, u.id]}) %>
	<%= f.submit%>
<% end %>

rails/colegio/app/views/homeworks/index.html.erb
<h1>Todas las tareas</h1>
<%= link_to "Nueva tarea", new_homework_path%>
<ul>
<% @homework.each do |h|%>
	<li>
 	<%= h.text %> de <strong> <%= h.subject.name %> </strong>, para el <%= h.final_date %>
 	<%= link_to "Eliminar", homework_path(h) , method: :delete, data: { confirm: "Sure?"} %>
		<%= link_to "Editar", edit_homework_path(h)%>
 	</li>
<% end %>
</ul>

rails/colegio/app/views/homeworks/new.html.erb
<h1>Nueva tarea par estudiantes</h1>

<%= form_for @homework do |f| %>
	<%= f.label :text %>
	<%= f.text_field :text %>
	<%= f.label :final_date %>
	<%= f.date_field :final_date %>
	<%= f.label :subject_id %>
	<%= f.select(:subject_id, Subject.all.collect {|u| [u.name, u.id]}) %>
	<%= f.submit%>
<% end %>

rails/colegio/app/views/teachers/edit.html.erb
<h1>Editar Profesor</h1>
<%= form_for @teacher do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :surname %>
	<%= f.text_field :surname %>
	<%= f.label :document %>
	<%= f.text_field :document %>
	<%= f.label :subject_id %>
	<%= f.select(:subject_id, Subject.all.collect {|u| [u.name, u.id]}) %>
	<%= f.submit %>
<% end %>

rails/colegio/app/views/teachers/index.html.erb
<h1>Todos los profesores</h1>
<%= link_to "Nuevo profesor", new_teacher_path %>
<ul>
<% @teacher.each do |t| %>
	<li>
		<%= t.name + " " + t.surname %>
		<%= link_to "Eliminar", teacher_path(t) , method: :delete, data: { confirm: "Sure?"} %>
		<%= link_to "Editar", edit_teacher_path(t)%>
		<ul>
			<li>Profesor de: <%= t.subject.name %></li>
		</ul>
	</li>
<% end %>
</ul>

rails/colegio/app/views/teachers/new.html.erb
<h1>Nuevo Profesor</h1>
<%= form_for @teacher do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :surname %>
	<%= f.text_field :surname %>
	<%= f.label :document %>
	<%= f.text_field :document %>
	<%= f.label :subject_id %>
	<%= f.select(:subject_id, Subject.all.collect {|u| [u.name, u.id]}) %>
	<%= f.submit %>
<% end %>